mod tetragon {
    // NOTE: Since this is generated by tonic theres nothing else we can do.
    #![allow(clippy::all)]
    tonic::include_proto!("tetragon");
}

pub use tetragon::*;

pub mod getevents;
pub use getevents::*;
